/*
 * Generated by JasperReports - 18/10/13 10:25
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class Report_1382066756403_855545 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_CUSTOM_VALUES = null;
    private JRFillParameter parameter_JASPER_REPORT = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_SORT_FIELDS = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_DYNAMICREPORTS_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_CONTEXT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_FILTER = null;
    private JRFillParameter parameter_startPageNumber_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_manufactureName = null;
    private JRFillField field_model = null;
    private JRFillField field_serialNumber = null;
    private JRFillField field_hostname = null;
    private JRFillField field_ipAddress = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_CUSTOM_VALUES = (JRFillParameter)pm.get("CUSTOM_VALUES");
        parameter_JASPER_REPORT = (JRFillParameter)pm.get("JASPER_REPORT");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_SORT_FIELDS = (JRFillParameter)pm.get("SORT_FIELDS");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_DYNAMICREPORTS_SCRIPTLET = (JRFillParameter)pm.get("DYNAMICREPORTS_SCRIPTLET");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_CONTEXT = (JRFillParameter)pm.get("REPORT_CONTEXT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_FILTER = (JRFillParameter)pm.get("FILTER");
        parameter_startPageNumber_SCRIPTLET = (JRFillParameter)pm.get("startPageNumber_SCRIPTLET");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_manufactureName = (JRFillField)fm.get("manufactureName");
        field_model = (JRFillField)fm.get("model");
        field_serialNumber = (JRFillField)fm.get("serialNumber");
        field_hostname = (JRFillField)fm.get("hostname");
        field_ipAddress = (JRFillField)fm.get("ipAddress");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_125_"); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_114_"); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_116_"); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_118_"); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_120_"); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_122_"); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_124_"); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_3_"); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_hostname.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)field_ipAddress.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)field_serialNumber.getValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.String)field_model.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.String)field_manufactureName.getValue()); //$JR_EXPR_ID=20$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_125_"); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_114_"); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_116_"); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_118_"); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_120_"); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_122_"); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_124_"); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_3_"); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_hostname.getOldValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)field_ipAddress.getOldValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)field_serialNumber.getOldValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.String)field_model.getOldValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.String)field_manufactureName.getOldValue()); //$JR_EXPR_ID=20$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_125_"); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_114_"); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_116_"); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_118_"); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_120_"); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_122_"); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_124_"); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((net.sf.dynamicreports.jasper.base.JasperCustomValues)parameter_CUSTOM_VALUES.getValue()).getValue("simpleExpression_3_"); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_hostname.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)field_ipAddress.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)field_serialNumber.getValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.String)field_model.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.String)field_manufactureName.getValue()); //$JR_EXPR_ID=20$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
